influx:
  user: spring
  password: spring
  url : http://192.168.1.54:8086
  database: home

spring:
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      ddl-auto : update
  datasource:
    url: jdbc:mysql://192.168.1.54:3306/home
    username: spring
    password: spring

logging:
  level:
    root: INFO
